openapi: 3.0.3
info:
  title: Uni Hub — Auth Module
  version: 1.0.0
  description: Authentication endpoints for Uni Hub API

paths:
  /api/v1/auth/register:
    post:
      tags: [Authentication]
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "../shared.yaml#/components/schemas/RegisterRequest"
            example:
              email: "student@example.com"
              password: "StrongPassword123"
              firstName: "John"
              lastName: "Doe"
      responses:
        "201":
          description: User registered successfully
          content:
            application/json:
              schema:
                $ref: "../shared.yaml#/components/schemas/SuccessResponse"
              example:
                success: true
                data:
                  user:
                    id: "uuid-123"
                    email: "student@example.com"
                    firstName: "John"
                    lastName: "Doe"
                    isVerified: false
                meta: {}
                timestamp: "2025-01-20T12:00:00Z"
        "400":
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: "../shared.yaml#/components/schemas/ErrorResponse"

  /api/v1/auth/login:
    post:
      tags: [Authentication]
      summary: Login user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "../shared.yaml#/components/schemas/LoginRequest"
            example:
              email: "student@example.com"
              password: "StrongPassword123"
      responses:
        "200":
          description: Login successful
          content:
            application/json:
              schema:
                $ref: "../shared.yaml#/components/schemas/LoginResponse"
              example:
                success: true
                data:
                  accessToken: "jwt-access-token"
                  refreshToken: "jwt-refresh-token"
                  user:
                    id: "uuid-123"
                    email: "student@example.com"
                    firstName: "John"
                    lastName: "Doe"
                meta: {}
                timestamp: "2025-01-20T12:00:00Z"
        "401":
          description: Invalid credentials
          content:
            application/json:
              schema:
                $ref: "../shared.yaml#/components/schemas/ErrorResponse"

  /api/v1/auth/refresh:
    post:
      tags: [Authentication]
      summary: Refresh the access token
      responses:
        "200":
          description: New access token created
          content:
            application/json:
              schema:
                $ref: "../shared.yaml#/components/schemas/TokenRefreshResponse"
              example:
                success: true
                data:
                  accessToken: "new-jwt-access-token"
                meta: {}
                timestamp: "2025-01-20T12:00:00Z"
        "401":
          description: Refresh token expired or invalid
          content:
            application/json:
              schema:
                $ref: "../shared.yaml#/components/schemas/ErrorResponse"

  /api/v1/auth/logout:
    post:
      tags: [Authentication]
      summary: Logout user
      responses:
        "200":
          description: Logged out successfully
          content:
            application/json:
              schema:
                $ref: "../shared.yaml#/components/schemas/SuccessResponse"
              example:
                success: true
                data:
                  message: "Logged out successfully"
                meta: {}
                timestamp: "2025-01-20T12:00:00Z"

  /api/v1/auth/verify-email:
    post:
      tags: [Authentication]
      summary: Verify user email
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "../shared.yaml#/components/schemas/VerifyEmailRequest"
            example:
              token: "verification-token"
      responses:
        "200":
          description: Email verified
          content:
            application/json:
              schema:
                $ref: "../shared.yaml#/components/schemas/SuccessResponse"
        "400":
          description: Invalid token
          content:
            application/json:
              schema:
                $ref: "../shared.yaml#/components/schemas/ErrorResponse"

  /api/v1/auth/forgot-password:
    post:
      tags: [Authentication]
      summary: Request password reset email
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "../shared.yaml#/components/schemas/ForgotPasswordRequest"
            example:
              email: "student@example.com"
      responses:
        "200":
          description: Email sent
          content:
            application/json:
              schema:
                $ref: "../shared.yaml#/components/schemas/SuccessResponse"

  /api/v1/auth/reset-password:
    post:
      tags: [Authentication]
      summary: Reset password using a token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "../shared.yaml#/components/schemas/ResetPasswordRequest"
            example:
              token: "reset-token"
              newPassword: "NewStrongPassword123"
      responses:
        "200":
          description: Password reset successful
          content:
            application/json:
              schema:
                $ref: "../shared.yaml#/components/schemas/SuccessResponse"
        "400":
          description: Invalid token or password
          content:
            application/json:
              schema:
                $ref: "../shared.yaml#/components/schemas/ErrorResponse"
